-- =============================================================================
-- 30_features_from_csv.sql (SIN variables)
-- =============================================================================
USE DATABASE OPTIMIZING_CLEAN_WATER_SUPPLY;

-- Cambia este valor cuando generes otra versión
-- (por ahora dejamos baseline_csv_v1)
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1) LANDSAT - TRAIN
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FEATURES.FEAT_LANDSAT_TRAIN AS
SELECT
  ROUND(TRY_TO_DOUBLE(LATITUDE), 5)  AS LAT_R,
  ROUND(TRY_TO_DOUBLE(LONGITUDE), 5) AS LON_R,
  COALESCE(
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
    TRY_TO_DATE(SAMPLE_DATE)
  ) AS SAMPLE_DATE,

  SHA2(
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LATITUDE), 5)) || '|' ||
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LONGITUDE), 5)) || '|' ||
    TO_VARCHAR(
      COALESCE(
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
        TRY_TO_DATE(SAMPLE_DATE)
      )
    ),
    256
  ) AS POINT_ID,

  'baseline_csv_v1'::STRING AS RUN_ID,
  'LANDSAT'::STRING AS SOURCE,

  TRY_TO_DOUBLE(NIR)    AS NIR,
  TRY_TO_DOUBLE(GREEN)  AS GREEN,
  TRY_TO_DOUBLE(SWIR16) AS SWIR16,
  TRY_TO_DOUBLE(SWIR22) AS SWIR22,
  TRY_TO_DOUBLE(NDMI)   AS NDMI,
  TRY_TO_DOUBLE(MNDWI)  AS MNDWI

FROM RAW.LANDSAT_FEAT_TRAIN
WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL
  AND SAMPLE_DATE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2) LANDSAT - VAL
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FEATURES.FEAT_LANDSAT_VAL AS
SELECT
  ROUND(TRY_TO_DOUBLE(LATITUDE), 5)  AS LAT_R,
  ROUND(TRY_TO_DOUBLE(LONGITUDE), 5) AS LON_R,
  COALESCE(
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
    TRY_TO_DATE(SAMPLE_DATE)
  ) AS SAMPLE_DATE,

  SHA2(
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LATITUDE), 5)) || '|' ||
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LONGITUDE), 5)) || '|' ||
    TO_VARCHAR(
      COALESCE(
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
        TRY_TO_DATE(SAMPLE_DATE)
      )
    ),
    256
  ) AS POINT_ID,

  'baseline_csv_v1'::STRING AS RUN_ID,
  'LANDSAT'::STRING AS SOURCE,

  TRY_TO_DOUBLE(NIR)    AS NIR,
  TRY_TO_DOUBLE(GREEN)  AS GREEN,
  TRY_TO_DOUBLE(SWIR16) AS SWIR16,
  TRY_TO_DOUBLE(SWIR22) AS SWIR22,
  TRY_TO_DOUBLE(NDMI)   AS NDMI,
  TRY_TO_DOUBLE(MNDWI)  AS MNDWI

FROM RAW.LANDSAT_FEAT_VAL
WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL
  AND SAMPLE_DATE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3) TERRACLIMATE - TRAIN
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FEATURES.FEAT_TERRACLIMATE_TRAIN AS
SELECT
  ROUND(TRY_TO_DOUBLE(LATITUDE), 5)  AS LAT_R,
  ROUND(TRY_TO_DOUBLE(LONGITUDE), 5) AS LON_R,
  COALESCE(
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
    TRY_TO_DATE(SAMPLE_DATE)
  ) AS SAMPLE_DATE,

  SHA2(
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LATITUDE), 5)) || '|' ||
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LONGITUDE), 5)) || '|' ||
    TO_VARCHAR(
      COALESCE(
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
        TRY_TO_DATE(SAMPLE_DATE)
      )
    ),
    256
  ) AS POINT_ID,

  'baseline_csv_v1'::STRING AS RUN_ID,
  'TERRACLIMATE'::STRING AS SOURCE,

  TRY_TO_DOUBLE(PET) AS PET

FROM RAW.TERRACLIMATE_FEAT_TRAIN
WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL
  AND SAMPLE_DATE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4) TERRACLIMATE - VAL
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FEATURES.FEAT_TERRACLIMATE_VAL AS
SELECT
  ROUND(TRY_TO_DOUBLE(LATITUDE), 5)  AS LAT_R,
  ROUND(TRY_TO_DOUBLE(LONGITUDE), 5) AS LON_R,
  COALESCE(
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
    TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
    TRY_TO_DATE(SAMPLE_DATE)
  ) AS SAMPLE_DATE,

  SHA2(
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LATITUDE), 5)) || '|' ||
    TO_VARCHAR(ROUND(TRY_TO_DOUBLE(LONGITUDE), 5)) || '|' ||
    TO_VARCHAR(
      COALESCE(
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'YYYY/MM/DD'),
        TRY_TO_DATE(SAMPLE_DATE, 'DD-MM-YYYY'),
        TRY_TO_DATE(SAMPLE_DATE)
      )
    ),
    256
  ) AS POINT_ID,

  'baseline_csv_v1'::STRING AS RUN_ID,
  'TERRACLIMATE'::STRING AS SOURCE,

  TRY_TO_DOUBLE(PET) AS PET

FROM RAW.TERRACLIMATE_FEAT_VAL
WHERE LATITUDE IS NOT NULL
  AND LONGITUDE IS NOT NULL
  AND SAMPLE_DATE IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5) Unificar por fuente
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE FEATURES.FEAT_LANDSAT AS
SELECT * FROM FEATURES.FEAT_LANDSAT_TRAIN
UNION ALL
SELECT * FROM FEATURES.FEAT_LANDSAT_VAL;

CREATE OR REPLACE TABLE FEATURES.FEAT_TERRACLIMATE AS
SELECT * FROM FEATURES.FEAT_TERRACLIMATE_TRAIN
UNION ALL
SELECT * FROM FEATURES.FEAT_TERRACLIMATE_VAL;

-- ---------------------------------------------------------------------------
-- 6) Checks
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW FEATURES.CHECK_FEATURE_COUNTS AS
SELECT 'LANDSAT_TRAIN' AS NAME, COUNT(*) AS N FROM FEATURES.FEAT_LANDSAT_TRAIN
UNION ALL
SELECT 'LANDSAT_VAL', COUNT(*) FROM FEATURES.FEAT_LANDSAT_VAL
UNION ALL
SELECT 'TERRACLIMATE_TRAIN', COUNT(*) FROM FEATURES.FEAT_TERRACLIMATE_TRAIN
UNION ALL
SELECT 'TERRACLIMATE_VAL', COUNT(*) FROM FEATURES.FEAT_TERRACLIMATE_VAL;

CREATE OR REPLACE VIEW FEATURES.CHECK_FEATURE_MATCH_TRAIN AS
SELECT
  COUNT(*) AS TRAIN_POINTS,
  COUNT(ls.POINT_ID) AS TRAIN_WITH_LANDSAT,
  COUNT(tc.POINT_ID) AS TRAIN_WITH_TERRACLIMATE
FROM CURATED.TRAIN_POINTS_DEDUP p
LEFT JOIN FEATURES.FEAT_LANDSAT_TRAIN ls
  ON ls.POINT_ID = p.POINT_ID AND ls.RUN_ID = 'baseline_csv_v1'
LEFT JOIN FEATURES.FEAT_TERRACLIMATE_TRAIN tc
  ON tc.POINT_ID = p.POINT_ID AND tc.RUN_ID = 'baseline_csv_v1';

CREATE OR REPLACE VIEW FEATURES.CHECK_FEATURE_MATCH_SUBMISSION AS
SELECT
  COUNT(*) AS SUB_POINTS,
  COUNT(ls.POINT_ID) AS SUB_WITH_LANDSAT,
  COUNT(tc.POINT_ID) AS SUB_WITH_TERRACLIMATE
FROM CURATED.SUBMISSION_POINTS_DEDUP p
LEFT JOIN FEATURES.FEAT_LANDSAT_VAL ls
  ON ls.POINT_ID = p.POINT_ID AND ls.RUN_ID = 'baseline_csv_v1'
LEFT JOIN FEATURES.FEAT_TERRACLIMATE_VAL tc
  ON tc.POINT_ID = p.POINT_ID AND tc.RUN_ID = 'baseline_csv_v1';

