USE DATABASE OPTIMIZING_CLEAN_WATER_SUPPLY;

-- 1) Estadísticos de imputación (medianas)
CREATE OR REPLACE TABLE FEATURES.IMPUTE_STATS_LANDSAT AS
SELECT
  MEDIAN(NIR)    AS MED_NIR,
  MEDIAN(GREEN)  AS MED_GREEN,
  MEDIAN(SWIR16) AS MED_SWIR16,
  MEDIAN(SWIR22) AS MED_SWIR22,
  MEDIAN(NDMI)   AS MED_NDMI,
  MEDIAN(MNDWI)  AS MED_MNDWI
FROM FEATURES.FEATURE_MART_TRAIN;

-- 2) Feature mart imputado
CREATE OR REPLACE TABLE FEATURES.FEATURE_MART_TRAIN_IMPUTED AS
SELECT
  m.POINT_ID,
  m.LAT_R,
  m.LON_R,
  m.SAMPLE_DATE,

  m.TOTAL_ALKALINITY,
  m.ELECTRICAL_CONDUCTANCE,
  m.DISSOLVED_REACTIVE_PHOSPHORUS,

  m.MONTH,
  m.DOY,
  m.SIN_DOY,
  m.COS_DOY,

  -- Landsat imputado con medianas
  COALESCE(m.NIR,    s.MED_NIR)    AS NIR,
  COALESCE(m.GREEN,  s.MED_GREEN)  AS GREEN,
  COALESCE(m.SWIR16, s.MED_SWIR16) AS SWIR16,
  COALESCE(m.SWIR22, s.MED_SWIR22) AS SWIR22,
  COALESCE(m.NDMI,   s.MED_NDMI)   AS NDMI,
  COALESCE(m.MNDWI,  s.MED_MNDWI)  AS MNDWI,

  -- TerraClimate (ya está completo)
  m.PET

FROM FEATURES.FEATURE_MART_TRAIN m
CROSS JOIN FEATURES.IMPUTE_STATS_LANDSAT s;

-- 3) Submission imputado (para consistencia)
CREATE OR REPLACE TABLE FEATURES.FEATURE_MART_SUBMISSION_IMPUTED AS
SELECT
  m.POINT_ID,
  m.LAT_R,
  m.LON_R,
  m.SAMPLE_DATE,

  m.MONTH,
  m.DOY,
  m.SIN_DOY,
  m.COS_DOY,

  COALESCE(m.NIR,    s.MED_NIR)    AS NIR,
  COALESCE(m.GREEN,  s.MED_GREEN)  AS GREEN,
  COALESCE(m.SWIR16, s.MED_SWIR16) AS SWIR16,
  COALESCE(m.SWIR22, s.MED_SWIR22) AS SWIR22,
  COALESCE(m.NDMI,   s.MED_NDMI)   AS NDMI,
  COALESCE(m.MNDWI,  s.MED_MNDWI)  AS MNDWI,

  m.PET
FROM FEATURES.FEATURE_MART_SUBMISSION m
CROSS JOIN FEATURES.IMPUTE_STATS_LANDSAT s;

-- 4) Checks
CREATE OR REPLACE VIEW FEATURES.CHECK_FEATURE_MART_IMPUTED_NULLS AS
SELECT
  SUM(IFF(NDMI IS NULL, 1, 0)) AS NULL_NDMI,
  SUM(IFF(MNDWI IS NULL, 1, 0)) AS NULL_MNDWI,
  SUM(IFF(SWIR22 IS NULL, 1, 0)) AS NULL_SWIR22,
  SUM(IFF(PET IS NULL, 1, 0)) AS NULL_PET
FROM FEATURES.FEATURE_MART_TRAIN_IMPUTED;


